Changes incorporating Review 1
niranjank2022/Namma-Bus pull request #1
Opened 2024-11-25 12:11 UTC by niranjank2022

- **Update .env and index.js for env variables**
- **Update Readme**
- **Added routes/auth section from admin.js, user.js**
- **Update user side code**

2024-11-25 14:04 UTC, srikoushik requested changes

2024-11-25 14:04 UTC, srikoushik commented on index.js
>  app.use("/user", userRoutes);
Sample

2024-11-26 12:51 UTC, Rithikaram29 commented on index.js
> +dotenv.config({path: "./.env"});
Omit the path if your .env file is in the root directory

2024-11-26 12:51 UTC, Rithikaram29 commented on index.js
>  app.use("/admin", adminRoutes);
For admin and user routes, add authorisation middleware for validating admin and user accessing their accounts.

2024-11-26 12:54 UTC, niranjank2022 commented on index.js
> +dotenv.config({path: "./.env"});
if I comment this line, the env variables are not imported. PORT becomes undefined.

2024-11-26 16:36 UTC, Rithikaram29 approved these changes

2024-11-26 16:53 UTC, merged